"""add_oauth_state_table

Revision ID: fac73c6a8081
Revises: 4f093e2284c1
Create Date: 2025-09-22 20:48:11.978301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac73c6a8081'
down_revision: Union[str, None] = '4f093e2284c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index('ix_oauth_states_expires_at', 'oauth_states', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_sessions_conversation_state'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_conversation_state'), 'sessions', ['conversation_state'], unique=False)
    op.drop_index('ix_oauth_states_expires_at', table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###