# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: "2.1.4"
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint and format with ruff
      run: |
        poetry run ruff check .
        poetry run ruff format --check .
    - name: Test with pytest and coverage
      run: |
        poetry run coverage run -m pytest
        poetry run coverage report
        poetry run coverage xml
        poetry run coverage html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
